name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.0'
        channel: 'stable'
        cache: true
        
    - name: Install dependencies
      run: |
        cd aether_corp_web
        flutter pub get
        
    - name: Run Flutter analyze
      run: |
        cd aether_corp_web
        flutter analyze --no-fatal-infos || true
        
    - name: Build Flutter web app
      run: |
        cd aether_corp_web
        flutter build web --release || {
          echo "❌ Build failed"
          exit 1
        }
        if [ ! -f "build/web/index.html" ]; then
          echo "❌ Build failed - index.html not found"
          echo "Build directory contents:"
          ls -la build/web/ || echo "Build directory doesn't exist"
          exit 1
        fi
        echo "✅ Build successful - index.html found"
        
    - name: Deploy to Cloudflare Pages
      run: |
        npm install -g wrangler@latest
        cd aether_corp_web/build/web
        wrangler pages deploy . \
          --project-name=aethercorp \
          --branch=main \
          --commit-hash=${{ github.sha }} \
          --commit-message="${{ github.event.head_commit.message }}"
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
